version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass # ルートユーザーのパスワード
      MYSQL_DATABASE: testdb # 自動で作られるDB名
      MYSQL_USER: user # 新しく作られるユーザー
      MYSQL_PASSWORD: userpass # ユーザーのパスワード
    volumes:
      - ./mysql-data:/var/lib/mysql # 永続化

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    tty: true
    depends_on:
      - db
  
  backend:
    build:
      context: ./lifestylehackbackend
    container_name: spring-dev
    ports:
      - "8080:8080"
    volumes:
      - ./lifestylehackbackend:/app
      - ~/.m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpass
    depends_on:
      - db
